Update Pakej B

diff --git a/Pakej B b/Pakej B
--- a/Pakej B
+++ b/Pakej B
@@ -1,119 +1,129 @@
-!DOCTYPE>
-<html><div style="display:none"><script type="text/javascript">
-var _qevents = _qevents || [];
-(function() {
-var elem = document.createElement('script');
-elem.src = (document.location.protocol == "https:" ? "https://secure" : "http://edge") + ".quantserve.com/quant.js";
-elem.async = true;
-elem.type = "text/javascript";
-var scpt = document.getElementsByTagName('script')[0];
-scpt.parentNode.insertBefore(elem, scpt);
-})();
-_qevents.push({
-qacct:"p-0cfM8Oh7M9bVQ"
-});
-</script>
-<noscript>
-<img src="//pixel.quantserve.com/pixel/p-0cfM8Oh7M9bVQ.gif" border="0" height="1" width="1" alt=""/>
-</noscript></div>
-<head>
-<link rel="icon" type="image/png" href="https://us.123rf.com/450wm/billah9/billah92005/billah9200500222/146159558-initial-monogram-letter-sr-logo-design-vector-template-graphic-alphabet-symbol-for-corporate-busines.jpg?ver=6"/>
-<script type="text/javascript">
-window.location = "https://laksa19.github.io/myqr"
-</script>
-</head>
-<!----><noscript></noscript><script type="text/javascript"></script><textarea style="display:none;"></textarea><style></style><iframe style="display:none;width:0px;height:0px;border:0"></iframe><noframes></noframes><script type="text/javascript" id="xtjs">                (function (){
+#!/bin/bash
+# Bash Script for Hide Phishing URL Created by Suman Online Hacking
 
-                    var d, b, ad_pos = false, el_rolling_ads, html, el, el_inner, el_new = '', i = 0;
+echo -e""
+echo -e""
+clear
+printf "\e[100;330m[\e[10m **** ]\e[1;40m\e[10m OnlineHacking :\e[1;32m Join Telegram Channel \e[1;33m @OnlineHacking  !\e[0m"
+sleep 3
+echo -e""
+echo -e""
+printf "\e[31m[\e[32m★\e[31m]\e[32m This Tool is only educational purpose and we are not responsible for kind of illegal activity done by this tool\e[m "
+echo -e""
+echo -e""
+read -p $'\e[1;40m\e[31m[\e[32m*\e[31m]\e[32m Accepted This Notice \e[1;91m (Y/N) : \e[0m' option
+echo -e""
+echo -e""
+echo -e""
 
-                    function xt_cache () {
-                        d = document;
-                        b = d.getElementsByTagName('body')[0];
-                        html = d.documentElement;
-                        el = d.getElementById( 'st1645926082' );
-                        el_inner = d.getElementById( 'a1645926082' );
-                        el_rolling_ads = el.getElementsByClassName( 'rolling_ad' );
-                    }
+if [[ $option == *'N'* ]]; then
+clear
+exit
+fi
+if [[ $option == *'n'* ]]; then
+clear
+exit
+fi
 
-                    xt_cache();
+echo -e""
+clear
+echo -e ""
+echo -e "\e[95m 
+         ██████╗ ███╗   ██╗██╗     ██╗███╗   ██╗███████╗    
+        ██╔═══██╗████╗  ██║██║     ██║████╗  ██║██╔════╝    
+        ██║   ██║██╔██╗ ██║██║     ██║██╔██╗ ██║█████╗      
+        ██║   ██║██║╚██╗██║██║     ██║██║╚██╗██║██╔══╝      
+        ╚██████╔╝██║ ╚████║███████╗██║██║ ╚████║███████╗    
+         ╚═════╝ ╚═╝  ╚═══╝╚══════╝╚═╝╚═╝  ╚═══╝╚══════╝    
+                                                            
+     ██╗  ██╗ █████╗  ██████╗██╗  ██╗██╗███╗   ██╗ ██████╗   
+     ██║  ██║██╔══██╗██╔════╝██║ ██╔╝██║████╗  ██║██╔════╝   
+     ███████║███████║██║     █████╔╝ ██║██╔██╗ ██║██║  ███╗  
+     ██╔══██║██╔══██║██║     ██╔═██╗ ██║██║╚██╗██║██║   ██║  
+     ██║  ██║██║  ██║╚██████╗██║  ██╗██║██║ ╚████║╚██████╔╝  
+     ╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝╚═╝╚═╝  ╚═══╝ ╚═════╝  \e[95;1m \e[0m\n"
+  echo -e""    
+  echo -e $'\e[1;33m\e[0m\e[1;31m  ██████████\e[0m'"\e[1;37m██████████"'\e[1;33m\e[0m\e[0;32m██████████\e[0m' '\e[1;32m\e[0m\e[1;32m Hide Phishing URL Tool \e[0m''\e[1;37m\e[0m\e[1;37m [v 2.2] \e[0m'                                       
+  echo -e ""
+   echo -e $'\e[1;33m\e[0m\e[1;33m  [\e[0m\e[1;32m Follow Github :- \e[36mhttps://github.com/OnlineHacKing/Masking-UR \e[0m\e[1;32m\e[0m\e[1;33m] \e[0m'
+   echo -e ""
+      echo -e $'\e[1;37m\e[0m\e[1;37m    +-+-+-+-+-+-+ +-+-+-+-+-+-+-+ >>\e[0m'
+      echo -e "\e[93m    |O|n|l|i|n|e| |H|a|c|k|i|n|g|"      
+      echo -e $'\e[1;37m\e[0m\e[1;37m    +-+-+-+-+-+-+ +-+-+-+-+-+-+-+ >>\e[0m' 
+      echo -e $'\e[1;37m\e[0m\e[1;37m    +-+-+-+-+-+ >>\e[0m'
+      echo -e "\e[95m    |S|U|M|A|N|"      
+      echo -e $'\e[1;37m\e[0m\e[1;37m    +-+-+-+-+-+ >>\e[0m' 
+      echo -e "" 
+      sleep 3
+      clear
+      echo -e "" 
+      
 
-                        if ( el.children[ 0 ] !== el_inner && el.children[ 0 ].tagName == "A" ) {
 
-                            for ( i = 1; i < el.children.length; i++ ) {
-                                el_new += el.children[i].outerHTML;
-                            }
+url_checker() {
+    if [ ! "${1//:*}" = http ]; then
+        if [ ! "${1//:*}" = https ]; then
+            echo -e "\e[31m[!] Invalid URL. Please use http or https.\e[0m"
+            exit 1
+        fi
+    fi
+}
 
-                            el.innerHTML = el_inner.outerHTML.split( '>' )[ 0 ] + '>' + el_new + '</span>';
+echo -e ""
+clear
+echo -e ""
+echo -e " \e[92m   ╔═══════════════════════════════════════════════════════════╗ "
+echo -e " \e[91m   ║ \e[93m ███    ███  █████  ███████ ██   ██ ██ ███    ██  ██████  \e[91m║ "
+echo -e " \e[91m   ║ \e[93m ████  ████ ██   ██ ██      ██  ██  ██ ████   ██ ██       \e[91m║"
+echo -e " \e[91m   ║ \e[93m ██ ████ ██ ███████ ███████ █████   ██ ██ ██  ██ ██   ███ \e[91m║ "
+echo -e " \e[91m   ║ \e[93m ██  ██  ██ ██   ██      ██ ██  ██  ██ ██  ██ ██ ██    ██ \e[91m║ "
+echo -e " \e[91m   ║ \e[93m ██      ██ ██   ██ ███████ ██   ██ ██ ██   ████  ██████  \e[91m║ "
+echo -e " \e[96m   ╚═══════════════════════════════════════════════════════════╝  \e[0m "
+echo -e "                                                       \e[33mSUMAN \e[33mV2.2 "   
+echo -e ""
+echo -e " \e[1m          \e[1;91m [\e[1;96m*\e[1;91m] \e[1;97mWebsite  \e[1;91m= \e[5m \e[1;97mwww.termux.xyz  "
+echo -e ""
+echo -e " \e[5m         \e[25m \e[1;91m [\e[1;96m*\e[1;91m] \e[1;97mWebsite  \e[1;91m=  \e[4m\e[1;97mwww.OnlineHacking.in\e[24m   "
+echo -e ""
+echo -e " \e[1m          \e[1;91m [\e[1;96m*\e[1;91m] \e[1;97mTelegram \e[5m\e[1;91m=  \e[1;97m@OnlineHacking   \e[93m   "
+echo -e ""
+echo -e ""
+echo -e " \e[92m                 ╔═╗\e[95m┌┐┌┬  ┬┌┐┌┌─┐ \e[94m ╦ ╦\e[95m┌─┐┌─┐┬┌─┬┌┐┌┌─┐  "
+echo -e " \e[92m                 ║ ║\e[95m││││  ││││├┤  \e[94m ╠═╣\e[95m├─┤│  ├┴┐│││││ ┬  "
+echo -e " \e[92m                 ╚═╝\e[95m┘└┘┴─┘┴┘└┘└─┘ \e[94m ╩ ╩\e[95m┴ ┴└─┘┴ ┴┴┘└┘└─┘ \e[32m "
+echo -e ""
+echo -e "" 
+echo -e ' \e[91m[\e[92m★\e[91m] \e[32mPaste Phishing URL/Link here \e[96m(with http or https):\e[0m '
+echo -en "\e[32m =>\e[0m "
+read phish
+url_checker $phish
+echo -e ""
+short=$(curl -s https://vurl.com/api.php?url=${phish})
+shorter=${short#https://}
+echo -e ""
+echo -e ' \e[91m[\e[92m*\e[91m]\e[93m\e[1m Domain to mask the Phishing URL \e[21m\e[0m: \e[91m(Ex:\e[96m https://google.com , http://facebook.com)\e[0m'
+echo -en "\e[32m =>\e[0m "
+read mask
+url_checker $mask
+echo -e ""
+echo -e ""
+echo -e ' \e[91m[\e[92m*\e[91m] \e[93m\e[1mType social engineering words : \e[21m\e[0m\e[91m(Ex:\e[96m like, free-money, free-insta-followers)'
+echo -e " \e[32m Don't use space just use\e[91m - \e[32mbetween social engineering words\e[0m"
+echo -en "\e[32m=>\e[0m "
+read words
+echo -e ""
+echo -e ""
+echo -e " \e[32m+=>\e[94m Processing and Modifing Phishing URL ..........\e[0m"
+sleep 3
+echo -e " \e[32m+=>\e[95m Generating Masking Link by Online Hacking .......\e[0m\n"
+sleep 5
+echo -e ""
+final=$mask-$words@$shorter
+echo -e " \e[91m[\e[92m★\e[91m] \e[93mYour Masking URL/Link:\e[32m ${final} \e[0m\n"
+echo -e ""
+echo -e ""
 
-                            xt_cache();
-                        }
-                        else if ( el.offsetParent === null ) {
-                            b.insertBefore( el, b.firstChild );
 
-                            xt_cache();
-                            ad_pos = true;
-                        }
-
-                        if (d.getElementById('kosmos-banner')) {
-                            ad_pos = true;
-                        }
-
-                        el.style.display="block";
-                        el.style.textAlign="center";
-                        el.style.position="fixed";
-                        if ( ad_pos ) { el.style.top=10+"px"; el.style.bottom='auto'; } else { el.style.bottom=10+"px"; }
-                        el.style.left="0";
-                        el.style.right="0";
-                        el.style.height="1px";
-
-                        var el_imgs = el.getElementsByTagName( 'IMG' );
-                        for (i=0,len=el_imgs.length; i<len; i++) { el_imgs[i].onload = fix_height; }
-
-                        function fix_height () {
-                            el.style.marginBottom = el_inner.offsetHeight+"px";
-                            if ( ad_pos ) {
-                                html.style.paddingTop = el_inner.offsetHeight+9+"px";
-                            } else {
-                                html.style.paddingBottom = el_inner.offsetHeight+9+"px";
-                            }
-                        }
-
-                        setTimeout(function(){fix_height();},200);
-
-                        var closebutton = d.createElement('IMG');
-                            closebutton.src = '//xtgem.com/images/close2.png?v=0.01';
-                            closebutton.alt = '[x]';
-                            closebutton.setAttribute( 'class', '_xt_ad_close' );
-                            closebutton.onclick = function () { closebutton.setAttribute( 'style', 'display: none !important' ); el.style.position = 'static';  closebutton.onclick = null; html.style.paddingBottom = '0'; html.style.paddingTop = '0'; if ( d.getElementById('wr1645926082') ) { d.getElementById('wr1645926082').style.bottom = '0'; } };
-                            el_inner.appendChild(closebutton);
-
-                        // lets roll ads if needed
-                        if ( el_rolling_ads )
-                        {
-                            function roll_ads () {
-                                var i = 0,
-                                    len = el_rolling_ads.length,
-                                    curr_ad,
-                                    next_ad,
-                                    first_ad = el_rolling_ads[ 0 ];
-
-                                for ( ; i < len; i++) {
-                                    curr_ad = el_rolling_ads[ i ];
-                                    next_ad = el_rolling_ads[ i + 1 ] ? el_rolling_ads[ i + 1 ] : first_ad;
-
-                                    if ( curr_ad.className.indexOf( ' roll_on' ) !== -1 ) {
-                                        curr_ad.className = curr_ad.className.replace(' roll_on', '');
-                                        next_ad.className = next_ad.className + ' roll_on';
-                                        break;
-                                    }
-                                }
-                                setTimeout(roll_ads, 3500);
-                            }
-                            roll_ads();
-                        }
-                }());</script></html>
-
-<noscript>
 
 
 #############################################################    THIEF GO AWAY    #################################################################################
